name: Test
on: push

jobs:
  test:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: [ubuntu, macOS, windows]
        node: [8, 10, 12, 14, 16, 17]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
        cache: 'npm'
    - name: Run tests for Node ${{ matrix.node }} on ${{ matrix.os }}
      run: npm cit
